load ..\run01\workspace_Selectie01_final.mat
%%load ..\loc_23-1\workspace_23.mat
%%AddWaveData('c:\Bosch\Bouwen_databases\loc_23-1\Oeverloc_23_WL_sorted.csv', 'c:\Bosch\Bouwen_databases\loc_23-1\Oeverloc_23_WL_wave.csv', 'c:\Bosch\Bouwen_databases\loc_23-1\tst_log01_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_run01_A_corr.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_run01_A_corr_wave.csv', 'c:\Bosch\Bouwen_databases\run01\run01_log_A_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_run01_B_corr.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_run01_B_corr_wave.csv', 'c:\Bosch\Bouwen_databases\run01\run01_log_B_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run02\run02_A_corr_sorted.csv', 'c:\Bosch\Bouwen_databases\run02\run02_A_corr10_sorted_wave.csv', 'c:\Bosch\Bouwen_databases\run02\run02_log_A10_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run02\run02_B_corr_sorted.csv', 'c:\Bosch\Bouwen_databases\run02\run02_B_corr10_sorted_wave.csv', 'c:\Bosch\Bouwen_databases\run02\run02_log_B10_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_result02.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_result02_wave.csv', 'c:\Bosch\Bouwen_databases\run01\tst_log02_wave.log','d:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_result02_a.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_result02_a_wave.csv', 'c:\Bosch\Bouwen_databases\run01\tst_log02_a_wave.log','d:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_result03a.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_result03a_wave.csv', 'c:\Bosch\Bouwen_databases\run01\tst_log03a_wave.log','d:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\sorted_result04.csv', 'c:\Bosch\Bouwen_databases\run01\sorted_result04_wave.csv', 'c:\Bosch\Bouwen_databases\run01\tst_log04_wave.log','d:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
AddWaveData('c:\Bosch\Bouwen_databases\run01\waves\test_Wfill_sorted.csv', 'c:\Bosch\Bouwen_databases\run01\waves\test_Wfill_sorted_waves.csv', 'c:\Bosch\Bouwen_databases\run01\waves\Wfill_log_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);
%%AddWaveData('c:\Bosch\Bouwen_databases\run01\run01_test.csv', 'c:\Bosch\Bouwen_databases\run01\run01_test_wave.csv', 'c:\Bosch\Bouwen_databases\run01\run01_log_test_wave.log','e:\WBI_data\RMM\2.Golven\','c:\Bosch\Bouwen_databases\workdir\',n_oever,oeverStat);