fileSaveDir         = 'd:\checkouts\hring_scripts\matlab\RingToets_LocationDefaults\output';

printHeader         = false;

fileName_NumSet     = 'NumericSettings.csv';
fileName_CalcTypes  = 'CalculationTypes.csv';
fileName_TimeInt    = 'TimeIntegrationSettings.csv';
fileName_ExclWDir   = 'ExcludedWindDirections.csv';
fileName_DesTable   = 'DesignTableSettings.csv';
fileName_ExclLocs   = 'ExcludedLocations.csv';
fileName_General    = 'General.csv';

%% Voorbeeld data
vb_NumSet     = [1400185, 1, 1, 12, 4, 150, 0.15, 0.005, 0.005, 2, 10000, 40000, 0.1000, -6, 6, 25];
vb_CalcTypes  = {1, 'Toetspeil'; ...
    2, 'QVariant'; ...
    3, 'Hs'; ...
    4, 'Tp'; ...
    5, 'Tm-1,0'; ...
    6, 'HBN'; ...
    7, 'GrasBinnenTalud'; ...
    8, 'KwHoogte'; ...
    9, 'KwSluiten'; ...
    10, 'KwPuntconstructies'; ...
    11, 'Duinen'};

vb_TimeInt    = [1400185, 1, 1; ...
    1400185, 2, 1; ...
    1400185, 3, 1; ...
    1400185, 4, 1; ...
    1400185, 5, 1; ...
    1400185, 6, 1];

vb_ExclWDir   = [1400185, 2, 9; ...
    1400185, 2, 10; ...
    1400185, 2, 11; ...
    1400185, 6, 10; ...
    1400185, 6, 11; ...
    1400185, 6, 12];

vb_DesTable   = [1400185, 1, 2.6, 4.1; ...
    1400185, 2, 1.326, 9.336; ...
    1400185, 6, 4.7, 8.9];

vb_ExclLocs   = [1400179; ...
    1400182];

vb_General    = {'25-10-2016' '14_10.sqlite' '25-12-2015' 5 'Oosterschelde'};

%% Numeric Settings
fid = fopen(fullfile(fileSaveDir, fileName_NumSet), 'w+');
if printHeader
    fprintf(fid, '%s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s\n', ...
        'LocationID', ...
        'MechanismID', ...
        'SubMechanismID', ...
        'CalculationMethod', ...
        'FORM_StartMethod', ...
        'FORM_NrIterations', ...
        'FORM_RelaxationFactor', ...
        'FORM_EpsHOH', ...
        'FORM_EpsZFunc', ...
        'DS_StartMethod', ...
        'DS_Min', ...
        'DS_Max', ...
        'DS_VarCoefficient', ...
        'NI_UMin', ...
        'NI_UMax', ...
        'NI_NumberSteps');
end

for iRow = 1:size(vb_NumSet,1)
    fprintf(fid, '%d; %d; %d; %d; %d; %d; %.3f; %.3f; %.3f; %d; %d; %d; %.3f; %d; %d; %d\n', ...
        vb_NumSet(iRow,:));
end

fclose(fid);

%% Calculation Types
fid = fopen(fullfile(fileSaveDir, fileName_CalcTypes), 'w+');
if printHeader
    fprintf(fid, '%s; %s\n', ...
        'CalculationTypeID', ...
        'CalculationType');
end

for iRow = 1:size(vb_CalcTypes,1)
    fprintf(fid, '%d; %s\n', ...
        vb_CalcTypes{iRow,:});
end

fclose(fid);

%% Time Integration Settings
fid = fopen(fullfile(fileSaveDir, fileName_TimeInt), 'w+');
if printHeader
    fprintf(fid, '%s; %s; %s\n', ...
        'LocationID', ...
        'CalculationTypeID', ...
        'TimeIntegrationSchemeID');
end

for iRow = 1:size(vb_TimeInt,1)
    fprintf(fid, '%d; %d; %d\n', ...
        vb_TimeInt(iRow,:));
end

fclose(fid);

%% Excluded Wind Directions
fid = fopen(fullfile(fileSaveDir, fileName_ExclWDir), 'w+');
if printHeader
    fprintf(fid, '%s; %s; %s\n', ...
        'LocationID', ...
        'CalculationTypeID', ...
        'ExcludedWindDirectionsID');
end

for iRow = 1:size(vb_ExclWDir,1)
    fprintf(fid, '%d; %d; %d\n', ...
        vb_ExclWDir(iRow,:));
end

fclose(fid);

%% Design Table Settings
fid = fopen(fullfile(fileSaveDir, fileName_DesTable), 'w+');
if printHeader
    fprintf(fid, '%s; %s; %s; %s\n', ...
        'LocationID', ...
        'CalculationTypeID', ...
        'Min', ...
        'Max');
end

for iRow = 1:size(vb_DesTable,1)
    fprintf(fid, '%d; %d; %4g; %4g\n', ...
        vb_DesTable(iRow,:));
end

fclose(fid);

%% Excluded Locations
fid = fopen(fullfile(fileSaveDir, fileName_ExclLocs), 'w+');
if printHeader
    fprintf(fid, '%s\n', ...
        'LocationID');
end

for iRow = 1:size(vb_ExclLocs,1)
    fprintf(fid, '%d\n', ...
        vb_ExclLocs(iRow,:));
end

fclose(fid);

%% General
fid = fopen(fullfile(fileSaveDir, fileName_General), 'w+');
if printHeader
    fprintf(fid, '%s; %s; %s; %s; %s\n', ...
        'CreationDate', ...
        'HRDName', ...
        'HRDCreationDate', ...
        'HRDTrackID', ...
        'HRDNameRegion');
end

for iRow = 1:size(vb_General,1)
    fprintf(fid, '%s; %s; %s; %d; %s\n', ...
        vb_General{iRow,:});
end

fclose(fid);