function GenerateSettingsMatFile(IDs, AreaVector, probMethod, FORMstart, DSminIter, DSmaxIter, timeIntegration, DesTabMinMax, varargin)

%% Settings
OPT = struct( ...
    'matFileDir',       '',    ...
    'matFileName',      ''      ...
    );

OPT = setproperty(OPT, varargin{:});

%% Area Vector
if isempty(AreaVector)
    AreaVector = ones(numel(IDs),1);
end


%% generate
NumSet  = [];
TimeInt = [];
DesTab  = [];
iLength = 24;

for iLoc = 1:numel(IDs)
    iArea = AreaVector(iLoc);
    NumSet  = [NumSet; IDs(iLoc)*ones(iLength,1), ...
        [1; 3; 11; 11; 11; 101; 101; 110; 110; 110; 111; 111; 111; 111; 111; 112; 112; 112; 112; 112; 112; 112; 112; 112], ...
        [1; 5; 11; 14; 16; 102; 103; 421; 422; 423; 422; 424; 425; 426; 427; 422; 424; 425; 430; 431; 432; 433; 434; 435], ...
        [probMethod.MHW(iArea); probMethod.QVar(iArea); probMethod.Waves(iArea); probMethod.Waves(iArea); probMethod.Waves(iArea); probMethod.HBN(iArea); probMethod.HBN(iArea); 11; 11; 11; 1; 11; 11; 1; 1; 1; 11; 11; 11; 1; 1; 1; 11; 11] ...
        [FORMstart.MHW(iArea); FORMstart.QVar(iArea); FORMstart.Waves(iArea); FORMstart.Waves(iArea); FORMstart.Waves(iArea); FORMstart.HBN(iArea); FORMstart.HBN(iArea); FORMstart.HBN(iArea); 1; FORMstart.HBN(iArea); 1; FORMstart.HBN(iArea); FORMstart.HBN(iArea); 1; 1; 1; FORMstart.HBN(iArea); FORMstart.HBN(iArea); FORMstart.HBN(iArea); 1; 1; 1; FORMstart.HBN(iArea); FORMstart.HBN(iArea)] ...
        150*ones(iLength,1) ...
        0.15*ones(iLength,1) ...
        0.005*ones(iLength,1) ...
        0.005*ones(iLength,1) ...
        0.005*ones(iLength,1) ...
        2*ones(iLength,1) ...
        [DSminIter.MHW(iArea); DSminIter.QVar(iArea); DSminIter.Waves(iArea); DSminIter.Waves(iArea); DSminIter.Waves(iArea); DSminIter.HBN(iArea); DSminIter.HBN(iArea); DSminIter.KW(iArea)*ones(17,1)]...
        [DSmaxIter.MHW(iArea); DSmaxIter.QVar(iArea); DSmaxIter.Waves(iArea); DSmaxIter.Waves(iArea); DSmaxIter.Waves(iArea); DSmaxIter.HBN(iArea); DSmaxIter.HBN(iArea); DSmaxIter.KW(iArea)*ones(17,1)]...
        0.1*ones(iLength,1) ...
        -6*ones(iLength,1) ...
        6*ones(iLength,1) ...
        25*ones(iLength,1)];
    
    TimeInt = [TimeInt; IDs(iLoc)*ones(10,1), ...
        [0;1;2;3;4;5;6;7;8;9], ...
        [timeIntegration.MHW(iArea); timeIntegration.QVar(iArea); timeIntegration.Waves(iArea); timeIntegration.Waves(iArea); timeIntegration.Waves(iArea); timeIntegration.HBN(iArea); timeIntegration.HBN(iArea); timeIntegration.KW(iArea); timeIntegration.KW_FBC(iArea); timeIntegration.KW(iArea)]];
    
    DesTab = [DesTab; IDs(iLoc)*ones(4,1), ...
        [0;1;2;5], ...
        [DesTabMinMax.Min_MHW(iArea); DesTabMinMax.Min_QVar(iArea); DesTabMinMax.Min_Waves(iArea); DesTabMinMax.Min_HBN(iArea)], ...
        [DesTabMinMax.Max_MHW(iArea); DesTabMinMax.Max_QVar(iArea); DesTabMinMax.Max_Waves(iArea); DesTabMinMax.Max_HBN(iArea)]];
end

save('-mat', fullfile(OPT.matFileDir, OPT.matFileName), 'NumSet', 'TimeInt', 'DesTab')

end