function GenerateSettingsCSVFiles

for iWS = 1:20
    
    if iWS < 10
        WaterSystem = ['0' num2str(iWS)];
    else
        WaterSystem = num2str(iWS);
    end
    
    matFileDir          = 'D:\checkouts\hring_scripts\matlab\RingToets_LocationDefaults\matFiles';
    matFileName         = [WaterSystem '_settings.mat'];
    
    fileSaveDir         = 'd:\checkouts\hring_scripts\matlab\RingToets_LocationDefaults\output';
    
    printHeader         = true;
    
    fileName_NumSet     = [WaterSystem '_NumericSettings.csv'];
    fileName_CalcTypes  = 'CalculationTypes.csv';
    fileName_TimeInt    = [WaterSystem '_TimeIntegrationSettings.csv'];
    fileName_DesTab     = [WaterSystem '_DesignTableSettings.csv'];
    
    %% Load settings
    load(fullfile(matFileDir, matFileName))
    
    %% Voorbeeld data
    
    CalcTypes  = {0, 'Toetspeil'; ...
        1, 'QVariant'; ...
        2, 'Hs'; ...
        3, 'Tp'; ...
        4, 'Tm-1,0'; ...
        5, 'HBN'; ...
        6, 'GrasBinnenTalud'; ...
        7, 'KwHoogte'; ...
        8, 'KwSluiten'; ...
        9, 'KwPuntconstructies'; ...
        10, 'Duinen'};
    
    %% Numeric Settings
    fid = fopen(fullfile(fileSaveDir, fileName_NumSet), 'w+');
    if printHeader
        fprintf(fid, '%s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s; %s\n', ...
            'LocationID', ...
            'MechanismID', ...
            'SubMechanismID', ...
            'CalculationMethod', ...
            'FORM_StartMethod', ...
            'FORM_NIterations', ...
            'FORM_RelaxationFactor', ...
            'FORM_EpsBeta', ...
            'FORM_EpsHOH', ...
            'FORM_EpsZFunc', ...
            'DS_StartMethod', ...
            'DS_Min', ...
            'DS_Max', ...
            'DS_VarCoefficient', ...
            'NI_UMin', ...
            'NI_UMax', ...
            'NI_NumberSteps');
    end
    
    for iRow = 1:size(NumSet,1)
        fprintf(fid, '%d; %d; %d; %d; %d; %d; %.3f; %.3f; %.3f; %.3f; %d; %d; %d; %.3f; %d; %d; %d\n', ...
            NumSet(iRow,:));
    end
    
    fclose(fid);
    
    %% Calculation Types
    fid = fopen(fullfile(fileSaveDir, fileName_CalcTypes), 'w+');
    if printHeader
        fprintf(fid, '%s; %s\n', ...
            'CalculationTypeID', ...
            'CalculationType');
    end
    
    for iRow = 1:size(CalcTypes,1)
        fprintf(fid, '%d; %s\n', ...
            CalcTypes{iRow,:});
    end
    
    fclose(fid);
    
    %% Time Integration Settings
    fid = fopen(fullfile(fileSaveDir, fileName_TimeInt), 'w+');
    if printHeader
        fprintf(fid, '%s; %s; %s\n', ...
            'LocationID', ...
            'CalculationTypeID', ...
            'TimeIntegrationSchemeID');
    end
    
    for iRow = 1:size(TimeInt,1)
        fprintf(fid, '%d; %d; %d\n', ...
            TimeInt(iRow,:));
    end
    
    fclose(fid);
    
    %% Design Table Settings
    fid = fopen(fullfile(fileSaveDir, fileName_DesTab), 'w+');
    if printHeader
        fprintf(fid, '%s; %s; %s; %s\n', ...
            'LocationID', ...
            'CalculationTypeID', ...
            'Min', ...
            'Max');
    end
    
    for iRow = 1:size(DesTab,1)
        fprintf(fid, '%d; %d; %4g; %4g\n', ...
            DesTab(iRow,:));
    end
    
    fclose(fid);
end
end